name: Access Website and Save Log

on:
  schedule:
    - cron: '0 1 * * *' # 每天凌晨 1 点执行
  workflow_dispatch: # 手动触发工作流
jobs:
  access-website:
    runs-on: ubuntu-latest

    steps:
      - name: Create access log
        run: |
          mkdir -p logs
          echo "Accessing website at $(date)" >> logs/access_log.txt
          curl -o /dev/null -s -w "%{http_code}\n" https://yfhao12.serv00.net >> logs/access_log.txt
          curl -o /dev/null -s -w "%{http_code}\n" https://yfhao1314.serv00.net >> logs/access_log.txt

      - name: Upload access log
        uses: actions/upload-artifact@v3
        with:
          name: access-log
          path: logs/access_log.txt
